export const API_CONFIG = {
  //localhost:3789
  BASE_URL: 'http://192.168.1.129:3789',
  AUTH_ENDPOINT: '/api/auth',
  TELLER_ENDPOINT: '/api/teller',
} as const;

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: `${API_CONFIG.BASE_URL}${API_CONFIG.AUTH_ENDPOINT}/login`,
    REGISTER: `${API_CONFIG.BASE_URL}${API_CONFIG.AUTH_ENDPOINT}/register`,
    PROFILE: `${API_CONFIG.BASE_URL}${API_CONFIG.AUTH_ENDPOINT}/profile`,
    CHANGE_PASSWORD: `${API_CONFIG.BASE_URL}${API_CONFIG.AUTH_ENDPOINT}/change-password`,
  },
  TELLER: {
    CONNECT: `${API_CONFIG.BASE_URL}${API_CONFIG.TELLER_ENDPOINT}/connect`,
    ACCOUNTS: `${API_CONFIG.BASE_URL}${API_CONFIG.TELLER_ENDPOINT}/accounts`,
    LINK: `${API_CONFIG.BASE_URL}${API_CONFIG.TELLER_ENDPOINT}/link`,
    SYNC_STATUS: `${API_CONFIG.BASE_URL}${API_CONFIG.TELLER_ENDPOINT}/sync-status`,
    NONCE: `${API_CONFIG.BASE_URL}${API_CONFIG.TELLER_ENDPOINT}/nonce`,
  },
} as const; 